### ISSUE TITLE
Clicking with mouse on menu breaks all buttons

### ISSUE THREAD

**Issue by MyntyPhresh** [walthill/production2#108]
Is an issue on the main menu and how-to-play menu, not the pause menu

**Comment by walthill** [comment]
Link to a code solution below. Might just be able to to `Cursor.visible = false` though
https://forum.unity.com/threads/left-mouse-click-breaks-ui-buttons-why-solved.417769/

**Comment by walthill** [comment]
abb8d99217ea772f9b31ae0a14952da652516544
