### ISSUE TITLE
sound boi no long has new tracks come in

### ISSUE THREAD

**Issue by Qazik** [walthill/production2#34]
Summary: sound boi doesn't pull in new parts properly

Commit:  9e66065

Expected Behavior: when going over a speed surface, new track should sweep in

Observed Behavior: that doesn't happen but when you change songs with the dev keys z and x, the new tracks are playing. Also sometimes they decide to stop looping

Reporduction Steps: go over a speed surface

Severity: MEDIUM

**Comment by walthill** [comment]
Seems to be working. Got the okay from @Qazik as well. Closing up shop on this one
