### ISSUE TITLE
[MED] Player wall-rides 

### ISSUE THREAD

**Issue by hagreiner** [walthill/production2#46]
Summary: player wall-rides and then continues to still skate sideways on the ground

Commit: https://github.com/walthill/production2/commit/7b1844d86a3272e9f2f91036505ec8b4e14e7c5a

Expected Behavior: I should not be able to wall ride

Observed Behavior: i was able to move slightly up and down the side of the wall, then once I fell was able to continue to skate on my side until I hit a curve and went back upright

Reproduction Steps: miss a jump and land on a building, slide to bottom, land on side, keep moving on side

Severity: MED - HIGH

**Comment by walthill** [comment]
This issue was fixed in the leadup to Game's Fest 6fe25983076c852497c0163c7b03b4190a8a2740
