### ISSUE TITLE
[LOW] noFriction physics material causes player jittering

### ISSUE THREAD

**Issue by walthill** [walthill/production2#51]
**Summary**: The player jitters when going up hill with the noFriction physics material attached. Especially noticeable with the camera turned fully in any one direction.

**Commit**: a78e66bb2775813003078a4740b441485f76b9f2

**Expected Behavior**: Player should skate smoothly along all ground surfaces without jittering

**Observed Behavior**:  When the player skates on an upward slope toward the lip of the bowl, the player character begins to jitter/shake

**Reproduction Steps**:  
1. Play game in Unity editor
2. Begin to skate on an upward slope in the bowl (preferably on the floor of the bowl itself)
3. Observe

**Severity**: LOW. Should be an easy fix. It appears removing the physics material removes the jittering as well.

**Comment by jacobnb** [comment]
Removed physics material, probably resolved but haven't tested
