### ISSUE TITLE
[HIGH] isGrounded is set to false while drifting up the side of the bowl

### ISSUE THREAD

**Issue by walthill** [walthill/production2#81]
Summary: Ground detection is sometimes incorrect

Commit: https://github.com/walthill/production2/commit/b7a234d89bd3ad20f0601ff5620b3ab32d487ad2

Expected Behavior: isGrounded = true when player is on ground

Observed Behavior: isGrounded = false when player drifts up the side of the bowl

Reproduction Steps: Get into the third speed channel and drift up the side of the bowl while watching isGrounded.

Severity: HIGH

**Comment by jacobnb** [comment]
Drift along the red line in speed channel two while watching the isGrounded variable
![](https://media.discordapp.net/attachments/547473279280087048/569196603697790997/unknown.png)
