### ISSUE TITLE
[MED] Camera jitters on angles

### ISSUE THREAD

**Issue by jacobnb** [walthill/production2#85]
Summary: Player jitters when going over any angle

Commit: https://github.com/walthill/production2/commit/9db10c97ddc3cd3efa490c15635878a2ee1852f8

Expected Behavior: Smooth movement

Observed Behavior: When a player goes over an angle at the right angle the camera jitters

Reproduction Steps: 
 _ _ 
|      \ hit the corner here
|

have to be in speed threshold 2+
Camera should jitter

Severity: MED because it's not completely game breaking but is irritating. "If you had epilepsy you would DIE!!!"

**Comment by walthill** [comment]
Found a good Unity Answers post https://answers.unity.com/questions/191268/strange-collision-behavior-bouncing-off-the-walls.html

**Comment by walthill** [comment]
Fix for getting stuck in walls and bouncing off of them 9024fb5868bdd57019e1b4bc6aea4406351b5238
