### ISSUE TITLE
[MED] Crouching isn't fully linked to the button

### ISSUE THREAD

**Issue by jacobnb** [walthill/production2#90]
Summary: The crouching animation isn't responsive and often lasts far longer than the actual crouch button press

Commit: https://github.com/walthill/production2/commit/2d95bb033034337ef8b79237fa40de00ceb35fa4

Expected Behavior: The player should crouch when B is pressed and un-crouch when B is released

Observed Behavior: The crouch animation lags behind the button press.

Reproduction Steps: Press and hold B while moving, observe delay between button press and animation.

MED - annoying visual bug

**Comment by harrygoetz** [comment]
Its nearly there, still some weirdness though
